# Generated by Django 4.2.5 on 2023-09-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CourseID", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=100)),
                ("StartTime", models.TimeField()),
                ("EndTime", models.TimeField()),
                ("ClassID", models.CharField(max_length=20)),
                ("classroom_no", models.CharField(max_length=10)),
                ("course_date", models.DateField()),
                (
                    "course_state",
                    models.CharField(choices=[(0, "0"), (1, "1")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "Course information",
                "verbose_name_plural": "course_information",
                "db_table": "d_course",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StudentID", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("stud_email", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(choices=[(0, "0"), (1, "1")], max_length=1),
                ),
                ("age", models.IntegerField()),
                ("stud_image", models.ImageField(blank=True, upload_to="studentImage")),
            ],
            options={
                "verbose_name": "student information",
                "verbose_name_plural": "student_information",
                "db_table": "d_student",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("TeacherID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("teac_email", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(choices=[(0, "0"), (1, "1")], max_length=1),
                ),
                ("age", models.IntegerField()),
                ("teac_image", models.ImageField(blank=True, upload_to="teacherImage")),
            ],
            options={
                "verbose_name": "teacher information",
                "verbose_name_plural": "teacher_information",
                "db_table": "d_teacher",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "CourseID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.course"
                    ),
                ),
                (
                    "StudentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollment",
                "db_table": "d_enrollment",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="TeacherID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.teacher"
            ),
        ),
    ]
