# Generated by Django 4.2.5 on 2023-09-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "AttendanceID",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "Present_status",
                    models.CharField(choices=[(0, "0"), (1, "1")], max_length=1),
                ),
                ("Absent_rate", models.FloatField()),
                ("Attendance_start_time", models.DateTimeField()),
                (
                    "CourseID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance",
                "db_table": "d_attendance",
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                ("Sta_ID", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "AttendanceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="basic.attendancereport",
                    ),
                ),
                (
                    "StudentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "student attendance",
                "verbose_name_plural": "student attendance",
                "db_table": "d_studentAttendance",
            },
        ),
    ]
