# Generated by Django 4.2.5 on 2023-09-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="StudentID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="CourseID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.course"
            ),
        ),
    ]
